---
title: "Mycobacterium concentrations in water"
author: "Camille Zimmer"
date: "2023-07-26"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


#Clear environment
rm(list = ls())

#Load libraries
library(tidyverse)
library(dplyr)
library(fitdistrplus)
library(readxl)
library(mc2d)
library(VGAM)

# Load the data into a dataframe 
raw_df <- read_excel("myco_conc_inwater.xlsx", skip = 0)
str(raw_df)

```

```{r data dist, fig.width=7, fig.height=7}

raw_df = filter(raw_df, pnq == "N")   

# First look
plotdist(raw_df$conc_perL, histo = TRUE, demp = TRUE)

# Next step: take log of conc data
raw_df = raw_df %>%
  mutate(log10_conc_perL = log10(conc_perL))
plotdist(raw_df$log10_conc_perL, histo = TRUE, demp = TRUE)

# Calculate skewness and kurtosis to investigate which distributions to use
# Regular data
descdist(raw_df$conc_perL, boot = 1000)
# Log10-transformed data
descdist(raw_df$log10_conc_perL, boot = 1000)

# OK, so it's... lognormal???
fln = fitdist(raw_df$conc_perL, "lnorm", method="mle") 
summary(fln)
# graph lognormal
par(mfrow = c(2, 2)) 
denscomp(fln) 
qqcomp(fln) 
cdfcomp(fln) 
ppcomp(fln)

# Try taking the normal distribution of the log10-transformed data? 
fn_log10 = fitdist(raw_df$log10_conc_perL, "norm", method="mle")
summary(fn_log10)
# graph it
par(mfrow = c(2, 2)) 
denscomp(fn_log10) 
qqcomp(fn_log10) 
cdfcomp(fn_log10) 
ppcomp(fn_log10)

# Try weibull and uniform for comparison
fw = fitdist(raw_df$conc_perL, "weibull", method="mle") 
summary(fw)
funi = fitdist(raw_df$conc_perL, "unif", method="mle") 
summary(funi)

# Graph them all
par(mfrow = c(2, 2)) 
plot.legend = c("Weibull", "lognormal", "uniform")
denscomp(list(fw, fln, funi), legendtext = plot.legend) 
qqcomp(list(fw, fln, funi), legendtext = plot.legend) 
cdfcomp(list(fw, fln, funi), legendtext = plot.legend) 
ppcomp(list(fw, fln, funi), legendtext = plot.legend)

```


```{r dummygrondbeefdata, fig.width=9, fig.height=9}
#non-normal dist 
# (Delignette-Muller & Dutang, 2015, 2020)
# https://www.jstatsoft.org/article/view/v064i04

#On selecting curve fitting:
# https://rstudio-pubs-static.s3.amazonaws.com/321514_6e8d1a04e2164ef7b56251eb1ffc19d8.html

data("groundbeef")
str(groundbeef)
plotdist(groundbeef$serving, histo = TRUE, demp = TRUE)

#Calculate skewness and kurtosis to investigate which distributions to use
descdist(groundbeef$serving, boot = 1000)

#Try different distributions
fw = fitdist(groundbeef$serving, "weibull") 
summary(fw)
fg = fitdist(groundbeef$serving, "gamma") 
summary(fg)
fln = fitdist(groundbeef$serving, "lnorm") 
summary(fln)

#Plots
par(mfrow = c(2, 2)) 
plot.legend = c("Weibull", "lognormal", "gamma")
denscomp(list(fw, fln, fg), legendtext = plot.legend) 
qqcomp(list(fw, fln, fg), legendtext = plot.legend) 
cdfcomp(list(fw, fln, fg), legendtext = plot.legend) 
ppcomp(list(fw, fln, fg), legendtext = plot.legend)
```